OH HAI
BTW WE TAEK TEXT MESAGEZ AN MAK EM BETTRZ
GIMMEH WATWUZSENTIN OUTTA BODY
LULZAPI IZ "http://www.callapi.info/home/lol/"
BTW POOPONIT! &WATWUZSENTIN&
GIMMEH LAL LULZ OUTTA &LULZAPI&&WATWUZSENTIN&
SO IM LIKE WERKING WITH TWIMML
    TWIMML IZ "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Response><Sms>&TWIMML&</Sms></Response>"
    I FOUND MAH TWIMML
KTHX
I HAS RESULTZ IZ WERKING(&LULZ&)
VISIBLE RESULTZ
INVISIBLE I HAS FINISHD BRB
KTHXBYE

