HAI
INVISIBLE FLICKR AND POWNCE API NICE, MAILCHIMP BETTAHS OM NOM NOM NOM ... CHALLENGE! http://www.youtube.com/watch?v=yYi61ZhSZ74
BTW This is from Tetraboy's original index.lol example. It shows defining a function, variable assignments, and incrememting numbers
MUST HAS STDIO
VISIBLEZ HAI WORLD!
I HAS COLOR1
I HAS COLOR2 IZ GREEN
COLOR1 IZ RED
VISIBLEZ COLOR1 = &COLOR1&
VISIBLEZ COLOR2 = &COLOR2&

BTW THIS IS A COMMENT
BTW THIS FUNC IS NAMED UPPING
SO IM LIKE UPPING WITH VAR VAR2=0
    VAR UPUP!
    I FOUND MAH VAR
KTHX
I HAS FOUR IZ UPPING(4)
VISIBLE FOUR UP? ITZA  
VISIBLEZ  FOUR
IVAR IZ 1
IVAR UPUP!
IVAR UPUP!
IZ &IVAR& == 1
    BTW IF
    VISIBLEZ YEAH RLY..
ORLY &IVAR& == 2
    BTW ELSEIF
    VISIBLEZ ORLY?
NOWAI
    BTW ELSE
    VISIBLEZ NOWAI!
KTHX
ALWAYZ SKY IZ BLUE
VISIBLE Teh sky iz 
VISIBLEZ __SKY__
NEWVAR IZ UPPING(3)
VISIBLEZ What is 2+2? &NEWVAR&


KTHXBYE

